name: Build APK

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Get sanitized branch name
        id: extract_branch
        run: |
          raw_branch=${GITHUB_REF#refs/heads/}
          sanitized_branch=${raw_branch//\//-}
          echo "branch=$sanitized_branch" >> $GITHUB_OUTPUT

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-build-${{ steps.extract_branch.outputs.branch }}
          path: build/app/outputs/flutter-apk/app-release.apk